### ISSUE TITLE
Reflecting XSS vulnerabilities in CMS Saurus v. 4.7 (Release-Date: 12.08.2014)

### ISSUE THREAD

**Issue by sroesemann** [sauruscms/Saurus-CMS-Community-Edition#61]
Dear ladies and gentlemen.

I found some reflecting XSS vulnerabilities in the current version of Saurus (v.4.7, release-date 12th-Aug-2014).

I am going to release an advisory on this (without technical details). Please provide me an email address here so I can submit you the technical details to patch the bugs. If I I don't hear anything from you until 21st January, I am going to release the technical details as well.

Thank you. Greetings.

Steffen Rösemann

**Comment by koosh** [comment]
Hey,

please contact me at reigo@saurus.ee with the details.

thank you.

**Comment by sroesemann** [comment]
Gonna send you an email in the next half hour! :-) Thank you for the fast answer!
